name: Checks

on:
  push:
    branches: [main]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Github token permissions
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: 'checks'
  cancel-in-progress: true

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Fetch grain binary
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'grain-lang/grain'
          version: 'tags/preview'
          file: 'grain-linux-x64'
          target: "bin/grain"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Install
        run: |
          chmod +x bin/grain
          ./bin/grain -v
      - name: Check Formatting
        run: |
          ./bin/grain format . -o .
          git diff --exit-code --name-only
      - name: Check Documentation
        run: |
          ./bin/grain doc . -o .
          git diff --exit-code --name-only
      - name: Run Tests
        run: |
          ./bin/grain ./grain-sexp/test.gr
          ./bin/grain ./grain-stream/test.gr
      